In [24]:
import os
from PIL import Image
import numpy as np
import cv2

In [25]:
Dir = os.path.dirname(os.path.abspath('UserAuth'))

In [26]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")


In [35]:
image_dir = os.path.join(Dir,"images")

In [36]:
cur_id = 0
labels_ids = {}
y_labels = []
x_train = []
for root,dirs,files in os.walk(image_dir):
    for file in files:
        if(file.endswith("png") or file.endswith("jpg")):
            path = os.path.join(root,file)
            label = os.path.basename(root).replace(" ","-").lower()
            print(label,path)
            if not label in labels_ids:
                labels_ids[label] = cur_id
                cur_id = cur_id+1
            id_got = labels_ids[label]
            print(id_got)
            pil_image = Image.open(path).convert("L") #grayScale
            image_array = np.array(pil_image,"uint8")
            print(image_array)
            faces = face_cascade.detectMultiScale(image_array,scaleFactor=1.5,minNeighbors=5)
            for (x,y,w,h) in faces:
                roi = image_array[y:y+h,x:x+w]
                x_train.append(roi)
                y_labels.append(id_got)
                

images C:\Users\AKASH JOY\Documents\UserAuth\images\foreign-2.jpg
0
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
images C:\Users\AKASH JOY\Documents\UserAuth\images\foreign-3.jpg
0
[[244 244 243 ... 252 252 252]
 [246 246 244 ... 252 252 252]
 [248 247 245 ... 253 253 253]
 ...
 [246 246 246 ... 240 240 240]
 [248 247 247 ... 238 239 240]
 [248 247 247 ... 238 239 240]]
images C:\Users\AKASH JOY\Documents\UserAuth\images\foreign-4.jpg
0
[[26 26 26 ... 42 42 41]
 [23 23 23 ... 37 37 37]
 [21 21 21 ... 45 44 44]
 ...
 [27 31 28 ... 54 52 49]
 [29 31 13 ... 56 53 50]
 [38 26 15 ... 58 55 51]]
images C:\Users\AKASH JOY\Documents\UserAuth\images\foreign-5.jpg
0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
johnnydeep C:\Users\AKASH JOY\Documents\UserAuth\images\JohnnyDeep\d